import { createAccessControl } from "better-auth/plugins/access";
import { defaultStatements as organizationDefaultStatements } from "better-auth/plugins/organization/access";

const organizationStatements = {
  ...organizationDefaultStatements,
  schedules: ["create", "read", "update", "delete"],
  products: ["create", "read", "update", "archive", "unarchive", "delete"],
  productCategories: ["create", "read", "update", "delete"],
  variationGroups: ["create", "read", "update", "delete"],
  modifiers: ["create", "read", "update", "delete"],
  ingredients: ["create", "read", "update", "delete"],
  supplies: ["create", "read", "update", "delete"],
  suppliers: ["create", "read", "update", "delete"],
  ingredientCategories: ["create", "read", "update", "delete"],
  supplyCategories: ["create", "read", "update", "delete"],
  taxes: ["create", "read", "update", "delete"],
  units: ["create", "read", "update", "delete"],
  orders: ["create", "read", "update", "delete"],
  coupons: ["create", "read", "update", "delete"],
  cashback: ["read", "update"],
  notifications: ["create", "read", "update"],
  uploads: ["create", "read", "update", "delete"],
  inventory: ["read", "adjust", "manage"],
  purchaseOrders: ["read", "manage", "receive"],
} as const;

export const ORGANIZATION_AC = createAccessControl(organizationStatements);

type OrganizationStatements = typeof ORGANIZATION_AC.statements;

export type OrganizationPermissions = {
  [K in keyof OrganizationStatements]?: OrganizationStatements[K][number][];
};

export const ORGANIZATION_ROLES = {
  owner: ORGANIZATION_AC.newRole({
    organization: ["update", "delete"],
    member: ["create", "update", "delete"],
    invitation: ["create", "cancel"],
    schedules: ["create", "read", "update", "delete"],
    products: ["create", "read", "update", "archive", "unarchive", "delete"],
    productCategories: ["create", "read", "update", "delete"],
    variationGroups: ["create", "read", "update", "delete"],
    modifiers: ["create", "read", "update", "delete"],
    ingredients: ["create", "read", "update", "delete"],
    supplies: ["create", "read", "update", "delete"],
    suppliers: ["create", "read", "update", "delete"],
    ingredientCategories: ["create", "read", "update", "delete"],
    supplyCategories: ["create", "read", "update", "delete"],
    taxes: ["create", "read", "update", "delete"],
    units: ["create", "read", "update", "delete"],
    orders: ["create", "read", "update", "delete"],
    coupons: ["create", "read", "update", "delete"],
    cashback: ["read", "update"],
    notifications: ["create", "read", "update"],
    uploads: ["create", "read", "update", "delete"],
    inventory: ["read", "adjust", "manage"],
    purchaseOrders: ["read", "manage", "receive"],
  }),
  admin: ORGANIZATION_AC.newRole({
    organization: ["update"],
    member: ["create", "update", "delete"],
    invitation: ["create", "cancel"],
    schedules: ["create", "read", "update", "delete"],
    products: ["create", "read", "update", "archive", "unarchive", "delete"],
    productCategories: ["create", "read", "update", "delete"],
    variationGroups: ["read"],
    modifiers: ["read"],
    ingredients: ["read"],
    supplies: ["read"],
    suppliers: ["create", "read", "update", "delete"],
    ingredientCategories: ["read"],
    supplyCategories: ["read"],
    taxes: ["read"],
    units: ["read"],
    orders: ["create", "read", "update", "delete"],
    coupons: ["create", "read", "update", "delete"],
    cashback: ["read", "update"],
    notifications: ["create", "read", "update"],
    uploads: ["create", "read"],
    inventory: ["read", "adjust", "manage"],
    purchaseOrders: ["read", "manage", "receive"],
  }),
  member: ORGANIZATION_AC.newRole({
    invitation: ["create"],
    schedules: ["read"],
    products: ["read"],
    productCategories: ["read"],
    variationGroups: ["read"],
    modifiers: ["read"],
    ingredients: ["read"],
    supplies: ["read"],
    suppliers: ["read"],
    ingredientCategories: ["read"],
    supplyCategories: ["read"],
    taxes: ["read"],
    units: ["read"],
    orders: ["create", "read"],
    coupons: ["read"],
    uploads: ["read"],
    inventory: ["read"],
    purchaseOrders: ["read"],
  }),
  barista: ORGANIZATION_AC.newRole({
    orders: ["read", "update"],
  }),
};
